# Generated by Django 3.0.8 on 2020-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketholder',
            name='ticket_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
